- name: NGINX | Install and configure NGINX
  hosts: web
  become: true

  roles:
    - install_nginx

- name: rsyslog | Install and configure log
  hosts: log
  become: true

  roles:
    - rsyslog

